### ISSUE TITLE
[bug] When skipping back while playing, server bans peer IPs due to 'piece failed hash'

### ISSUE THREAD

**Issue by darkblaze69** [YouROK/TorrServer#95]
Using latest MatriX.104 on separate Linux box and latest apk via Nova Player.
When rewinding back while playing a torrent, server bans peer IPs due to 'piece failed hash'.
Logs say:

```
NONE  client.go:1200: banning ip [scrubbed ip]
NONE  torrent.go:1556: "Мортал Комбат.2021.UHD.Blu-Ray.Remux.2160p.mkv": piece failed hash: 19 connections contributed
NONE  client.go:1200: banning ip [scrubbed ip]
NONE  torrent.go:1556: "Мортал Комбат.2021.UHD.Blu-Ray.Remux.2160p.mkv": piece failed hash: 18 connections contributed
NONE  client.go:1200: banning ip [scrubbed ip]
NONE  torrent.go:1556: "Мортал Комбат.2021.UHD.Blu-Ray.Remux.2160p.mkv": piece failed hash: 17 connections contributed
NONE  client.go:1200: banning ip [scrubbed ip]
```

So if we have 3 active seeders for torrent, in about 3-5 skippings back in a row there are 0 seeders left available, because they're all banned by server. That's a huge problem.

**Comment by VuzzyM** [comment]
@darkblaze69 Вы тестировали это на других плеерах?  Например медиаплеер Vimu.

**Comment by VuzzyM** [comment]
@tsynik @YouROK в vimu такого не встречал, даже в just player, в mx player и nova такая проблема

**Comment by tsynik** [comment]
@darkblaze69 good point. it was always so, but only with last build message was exposed to log. there is no easy fix, so just know it's better not rewind back on such torrents ;-)

**Comment by tsynik** [comment]
probably fixed with 53eb769e13d87e6de6d2ac8c778c5d35102d1023 but there is no IP ban at all in that case - can have side effects

**Comment by SanekP** [comment]
Still have this issue.
However it doesn't say "banning ip" anymore, it is actually banned (not used) after log
2021-09-15T16:51:47+0300 WARN  torrent.go:1540: "Aladdin.2019.UHD.BDRemux.2160p.HDR.IVA(RUS.UKR.ENG).ExKinoRay": piece 2179 failed hash: 5 connections contributed

It is very noticeable when there are few seeders. After restarting app it is able to connect to "banned" peer.
Also this happens not only after rewinding but when putting on pause.

@tsynik could you reopen this issue?

**Comment by tsynik** [comment]
> Still have this issue.
> However it doesn't say "banning ip" anymore, it is actually banned (not used) after log
> 2021-09-15T16:51:47+0300 WARN torrent.go:1540: "Aladdin.2019.UHD.BDRemux.2160p.HDR.IVA(RUS.UKR.ENG).ExKinoRay": piece 2179 failed hash: 5 connections contributed
> It is very noticeable when there are few seeders. After restarting app it is able to connect to "banned" peer.
> Also this happens not only after rewinding but when putting on pause.
> @tsynik could you reopen this issue?

There is no IP ban on this case anymore. Torrent still can use those connections. You can also try torrserver versions with .NE in it's name from Telegram channel - they use actual not outdated anacrolix@torrent engine and behavior can differ. There is nothing we can do in TorrServer - this issue related to torrent itself.
